version: '3.8'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - '3000:3000'
    volumes:
      - .:/app

